# This is a basic workflow to help you get started with Actions

name: CIAICEDI-Hum

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a second one script
        run: pwd && ls -la 

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cat /etc/os-release
          uptime
          df -h
          uname -a 
          echo "é o fim brasil "

      # Create Virtual Environment
      - name: Set up Python Virtual Environment
        run: |
          python -m venv venv
          
      # Activate virtual environment
      - name: Activate Virtual Environment
        run: . venv/bin/activate
      
      # Install requirements using pip
      - name: Install requirements
        run: |
          pip install -r requirements.txt
    
      # Run python main.py again
      - name: Run Python Script
        run: python main.py
